# Settings folder, controlling functions of the test
# DO NOT RENAME FOLDER OR REMOVE THESE FIRST TWO LINES
Questions: 1
AnswersPerQuestion: 4
TeamGUI: true
CategoryGUI: false
JSONfilename: data.json
Accessable: true
SafetyTestGuides: true
RequiresUsername: true
TypeofTest: Tooling
SetCategory: true