# Settings folder, controlling functions of the test
# DO NOT RENAME FOLDER OR REMOVE THESE FIRST TWO LINES
Questions: 16
AnswersPerQuestion: 4
TeamGUI: true
CategoryGUI: true
JSONfilename: data.json
Accessable: true
SafetyTestGuides: true
RequiresUsername: true
TypeofTest: General
SetCategory: false